# Site settings
title: "Web Hacker"
header-img: "img/facebook.jpg"
#email: your-email@domain.com
description: "高一宸"
url: "http://gycg.github.com" # the base hostname & protocol for your site

#github_username: gycg
zhihu_username: gycg

# Build settings
markdown: kramdown
