# Site settings
title: "Web Hacker"
header-img: "img/facebook.jpg"
description: "高一宸"
baseurl: ""
url: "http://gycg.github.com" # the base hostname & protocol for your site

# About/contact
owner:
    name: "gycg"
    email: gyc19950117@gmail.com
    bio: ""

# Data
favicon: img/favicon.png
github_username: gycg
zhihu_username: gycg

# Build settings
#markdown: redcarpet
#redcarpet:
#    extensions: ["tables"]

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Chongqing

# Defaults for posts:
defaults:
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "posts"
        author: "gycg"
        header-img: "img/facebook.jpg"

#Comments
comments :
    provider : duoshuo
    duoshuo :
        short_name : gycg
gems: [jekyll-paginate]
