# Site settings
title: "高一宸的个人博客"
header-img: "img/facebook.jpg"
#email: your-email@domain.com
description: "高一宸|个人博客"
url: "http://gycg.github.com" # the base hostname & protocol for your site

#github_username: gycg
zhihu_username: gycg

# Build settings
markdown: kramdown
